# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: GitHub Pelican Build Action
        # You may pin to the exact commit or the version.
        # uses: iranzo/gh-pages-pelican-action@c27d99dd96c4137b3e6894aaf32bf89bb022214a
        uses: iranzo/gh-pages-pelican-action@1.0.3
        with:
          # override the default `gh-pages` deployment branch
          GH_PAGES_BRANCH: gh-pages # optional, default is gh-pages
          # override the default `content` folder for sources for website
          SOURCE_FOLDER: content # optional, default is content
          # override the default `pelicanconf.py` file for pelican configuration
          PELICAN_CONFIG_FILE: pelicanconf.py # optional, default is pelicanconf.py
